version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      - deploy:
          name: haeserver
          command: ssh -o "StrictHostKeyChecking no" ${SSHUSERNAME}@${SSHIPADDRESS} "cd /var/www/html/testDeploy/circle-node-sample; git pull; npm install; pm2 start ./src/server.js"
