version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - add_ssh_keys
      - run: npm install
      - deploy:
          name: haeserver
          command: ssh -o "StrictHostKeyChecking no" $(eval echo ${SSHACCESS} | cut -c1-17) "cd /var/www/html/testDeploy/circle-node-sample; git pull; npm install; pm2 start ../../haePM2.config.js"
